// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Vehicle is an autogenerated mock type for the Vehicle type
type Vehicle struct {
	mock.Mock
}

// Accelerate provides a mock function with no fields
func (_m *Vehicle) Accelerate() {
	_m.Called()
}

// GetInfo provides a mock function with no fields
func (_m *Vehicle) GetInfo() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SlowDown provides a mock function with no fields
func (_m *Vehicle) SlowDown() {
	_m.Called()
}

// NewVehicle creates a new instance of Vehicle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVehicle(t interface {
	mock.TestingT
	Cleanup(func())
}) *Vehicle {
	mock := &Vehicle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
